#!/bin/python3

'''
Given the path to an orbit test data JSON file, generates orbit_test_cases.rs

See https://github.com/OpenStarscape/starscape-protocol/tree/master/orbit-tests for input data
'''

import json
import os
import sys
import math

data_url = 'https://github.com/OpenStarscape/starscape-protocol/tree/master/orbit-tests'

# Find output path
output_path = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'orbit_test_cases.rs')

if len(sys.argv) < 2:
    print('no input file')
    exit(1)
elif len(sys.argv) > 2:
    print('too many arguments')
    exit(1)
elif sys.argv[1] == '--help' or sys.argv[1] == '-h':
    print('USAGE: generate-orbit-test-cases.py /path/to/orbit-test-data.json')
    print('Get test data from ' + data_url)
    exit(0)
else:
    test_data_path = sys.argv[1]

with open(test_data_path, 'r') as f:
    test_data = json.loads(f.read())

print('Loaded ' + str(len(test_data)) + ' test cases')

# Variables used as dictionary keys (results in slightly prettier code)
name = 'name'
orbit = 'orbit'
grav_param = 'grav_param'
period_time = 'period_time'
at_time = 'at_time'
position = 'position'
velocity = 'velocity'

script_path = 'src/' + os.path.realpath(__file__).split('/src/')[-1]
code = '''//! AUTOGENERATED by ''' + script_path+ ''' -- DO NOT EDIT
//! See ''' + data_url + ''' for orbit test documentation

use super::*;
'''

def format_floats(array, names, indent):
    assert len(array) == len(names)
    lines = []
    for item in array:
        line = '\n'
        line += '    ' * indent
        line += str(float(item))
        line += ','
        lines.append(line)
    for i in range(len(names)):
        lines[i] += ' ' * (32 - len(lines[i]))
        lines[i] += '// ' + names[i]
    return ''.join(lines)

def format_struct(array, names, indent):
    assert len(array) == len(names)
    lines = []
    for i in range(len(array)):
        line = '\n'
        line += '    ' * indent
        line += names[i] + ': ' + str(float(array[i]))
        line += ','
        lines.append(line)
    return ''.join(lines)

# names used in Rust code
orbit_param_names = [
    'semi_major',
    'semi_minor',
    'inclination',
    'ascending_node',
    'periapsis',
    'base_time',
    'period_time',
]
pos_names = ['x', 'y', 'z']
vel_names = ['dx', 'dy', 'dz']

def make_test_case(test, suffix, fn, pos_offset, vel_offset):
    fn_name = test[name].replace(' ', '_') + suffix
    result = '''
#[test]
fn ''' + fn_name + '''() {
    ''' + fn + '''(
        OrbitData{''' + format_struct(test[orbit], orbit_param_names, 3) + '''
            parent: EntityKey::null(),
        },''' + format_floats([test[grav_param], test[at_time]], ['grav_param', 'at_time'], 2) + '''
        // body position
        Point3::new(''' + format_floats(test[position], pos_names, 3) + '''
        ),
        // body velocity
        Vector3::new(''' + format_floats(test[velocity], vel_names, 3) + '''
        ),'''
    if pos_offset is not None and vel_offset is not None:
        result += '''
        // position offset
        Point3::new(''' + format_floats(pos_offset, pos_names, 3) + '''
        ),
        // velocity offset
        Vector3::new(''' + format_floats(vel_offset, vel_names, 3) + '''
        ),'''
    result += '''
    );
}
'''
    return result;

output_cases = 0
for test in test_data:
    code += make_test_case(test, '_at_origin', 'static_orbit_test', [0, 0, 0], [0, 0, 0])
    code += make_test_case(test, '_with_offsets', 'static_orbit_test', [12, -500, 106.7], [-88, 123, -68.4])
    code += make_test_case(test, '_dynamic', 'dynamic_orbit_test', None, None)
    output_cases += 3

# Delete output file if it already exists
if os.path.exists(output_path):
    print(output_path + ' exists, deleting…')
    os.remove(output_path)

# Write output files
print('writing ' + str(output_cases) + ' tests to ' + output_path + '…')
with open(output_path, 'w') as f:
    f.write(code)

print('done')
